import {
  parseBrandPrefix,
  parseCategoryPrefix,
  generateSuggestedArticle,
  generateSku,
} from './sku.ts';
import {
  generateCode128Barcode,
  analyzeBarcode,
} from './barcode.ts';
import {
  validateAndNormalizeProductPricing,
  PricingPolicy,
} from '../schemas/productSchema.ts';

export type DuplicateStrategy = 'MERGE' | 'OVERWRITE' | 'SKIP';

export const PRODUCT_CSV_SCHEMA_KEYS = [
  'article',
  'name',
  'brand',
  'category',
  'sku',
  'barcode',
  'cost_price',
  'min_price',
  'max_price',
  'total_stock',
  'low_stock_limit',
  'primary_image_url',
  'description',
] as const;

export type ProductCsvFieldKey = (typeof PRODUCT_CSV_SCHEMA_KEYS)[number];

export interface ParsedCsvProductRow {
  rowNumber: number;
  rawRow: Record<string, string>;
  article: string;
  name: string;
  brand: string;
  category: string;
  sku: string;
  barcode: string;
  cost_price: number;
  selling_price: number;
  min_price: number;
  max_price: number;
  total_stock: number;
  low_stock_limit: number;
  primary_image_url: string;
  description: string;
  autoGeneratedFields: string[];
  validationErrors: Record<string, string>;
  isValid: boolean;
  isDuplicate: boolean;
  duplicateMatchType?: 'barcode' | 'article' | 'sku';
  existingProduct?: any;
  duplicateAction?: DuplicateStrategy;
}

/**
 * Generates a Sample CSV string using the exact database schema field keys
 * and dynamic settings from companySettings.
 */
export function generateSampleProductsCsv(companySettings: any): string {
  const header = PRODUCT_CSV_SCHEMA_KEYS.join(',');
  const defaultLowStock = companySettings?.low_stock_limit ?? companySettings?.lowStockLimit ?? 5;

  // Row 1: Complete row (demonstrates explicit values; barcode left blank to show Code-128 auto-generation)
  const row1 = [
    'NK-AIR-90',
    'Nike Air Max 90',
    'Nike',
    'Men',
    '',
    '',
    '3200',
    '4500',
    '4200',
    '4500',
    '12',
    String(defaultLowStock),
    '',
    'Men running footwear',
  ].join(',');

  // Row 2: Blank article, name, sku, barcode, brand, category (demonstrates full dynamic auto-generation)
  const row2 = [
    '',
    '',
    '',
    '',
    '',
    '',
    '1800',
    '2600',
    '',
    '',
    '8',
    '',
    '',
    'Auto-generated article, title, brand, category & barcode',
  ].join(',');

  // Row 3: Brand & Category provided, article/sku/barcode blank
  const row3 = [
    '',
    'Bata Formal Oxford',
    'Bata',
    'Women',
    '',
    '',
    '2400',
    '3400',
    '3100',
    '3400',
    '6',
    String(defaultLowStock),
    '',
    'Classic leather footwear',
  ].join(',');

  return `${header}\n${row1}\n${row2}\n${row3}\n`;
}

/**
 * RFC-4180 compliant CSV line splitter supporting quoted fields and escaped quotes.
 */
function splitCsvLine(line: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (ch === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += ch;
    }
  }
  result.push(current.trim());
  return result;
}

/**
 * Maps header aliases to canonical database schema column names.
 */
function normalizeHeaderKey(rawHeader: string): string {
  const clean = rawHeader
    .trim()
    .replace(/^["']|["']$/g, '')
    .trim();
  const lower = clean.toLowerCase().replace(/[\s-]+/g, '_');

  const map: Record<string, ProductCsvFieldKey> = {
    article: 'article',
    article_number: 'article',
    name: 'name',
    title: 'name',
    product_name: 'name',
    brand: 'brand',
    brand_name: 'brand',
    brandname: 'brand',
    category: 'category',
    category_name: 'category',
    categoryname: 'category',
    sku: 'sku',
    barcode: 'barcode',
    cost_price: 'cost_price',
    costprice: 'cost_price',
    selling_price: 'selling_price',
    sellingprice: 'selling_price',
    sale_price: 'selling_price',
    saleprice: 'selling_price',
    price: 'selling_price',
    min_price: 'min_price',
    minprice: 'min_price',
    min_sale_price: 'min_price',
    minsaleprice: 'min_price',
    max_price: 'max_price',
    maxprice: 'max_price',
    max_sale_price: 'max_price',
    maxsaleprice: 'max_price',
    total_stock: 'total_stock',
    totalstock: 'total_stock',
    stock: 'total_stock',
    low_stock_limit: 'low_stock_limit',
    lowstocklimit: 'low_stock_limit',
    primary_image_url: 'primary_image_url',
    primaryimageurl: 'primary_image_url',
    image_url: 'primary_image_url',
    description: 'description',
  };

  return map[lower] || lower;
}

/**
 * Parses CSV text and applies exact ProductFormModal & global companySettings
 * auto-generation, fallback, pricing validation, and duplicate detection rules.
 */
export function parseAndValidateProductsCsv(
  csvText: string,
  existingProducts: any[],
  companySettings: any,
  startingProductId: number
): {
  rows: ParsedCsvProductRow[];
  parseError?: string;
} {
  const lines = csvText
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .split('\n')
    .filter((l) => l.trim().length > 0);

  if (lines.length < 2) {
    return {
      rows: [],
      parseError: 'CSV file must contain a header row and at least one product data row.',
    };
  }

  const rawHeaders = splitCsvLine(lines[0]);
  const headers = rawHeaders.map(normalizeHeaderKey);

  const pricingPolicy: PricingPolicy =
    String(
      companySettings?.pricing_mode ||
        companySettings?.pricingMode ||
        companySettings?.pricingPolicy ||
        'FIXED'
    ).toUpperCase() === 'NEGOTIABLE'
      ? 'NEGOTIABLE'
      : 'FIXED';

  const defaultLowStockLimit =
    Number(companySettings?.low_stock_limit ?? companySettings?.lowStockLimit) || 5;

  // Track used barcodes, articles, and SKUs across DB + current CSV batch to prevent collisions
  const usedBarcodes = new Set<string>(
    existingProducts.map((p) => String(p.barcode || '').trim()).filter(Boolean)
  );
  const usedArticles = new Set<string>(
    existingProducts.map((p) => String(p.article || '').trim().toUpperCase()).filter(Boolean)
  );
  const usedSkus = new Set<string>(
    existingProducts.map((p) => String(p.sku || '').trim().toUpperCase()).filter(Boolean)
  );

  let nextCandidateId = Math.max(1, startingProductId || 1);
  const parsedRows: ParsedCsvProductRow[] = [];

  for (let i = 1; i < lines.length; i++) {
    const cells = splitCsvLine(lines[i]);
    // Skip completely empty rows
    if (cells.every((c) => c.trim() === '')) continue;

    const rawRow: Record<string, string> = {};
    headers.forEach((h, idx) => {
      rawRow[h] = cells[idx] !== undefined ? cells[idx].trim() : '';
    });

    const autoGeneratedFields: string[] = [];
    const validationErrors: Record<string, string> = {};

    // 1. Check if this row matches an existing product in database (by barcode, article, or sku)
    const inputBarcode = (rawRow.barcode || '').trim();
    const inputArticle = (rawRow.article || '').trim().toUpperCase();
    const inputSku = (rawRow.sku || '').trim().toUpperCase();

    let existingProduct: any = undefined;
    let duplicateMatchType: 'barcode' | 'article' | 'sku' | undefined = undefined;

    if (inputBarcode) {
      existingProduct = existingProducts.find(
        (p) => String(p.barcode || '').trim() === inputBarcode
      );
      if (existingProduct) duplicateMatchType = 'barcode';
    }
    if (!existingProduct && inputArticle) {
      existingProduct = existingProducts.find(
        (p) => String(p.article || '').trim().toUpperCase() === inputArticle
      );
      if (existingProduct) duplicateMatchType = 'article';
    }
    if (!existingProduct && inputSku) {
      existingProduct = existingProducts.find(
        (p) => String(p.sku || '').trim().toUpperCase() === inputSku
      );
      if (existingProduct) duplicateMatchType = 'sku';
    }

    const rowProductId =
      existingProduct?.tenantProductNo ||
      existingProduct?.tenant_product_no ||
      existingProduct?.id ||
      nextCandidateId;

    // 2. Brand (fallback from ProductFormModal: 'Local')
    let brand = (rawRow.brand || '').trim();
    if (!brand) {
      brand = existingProduct?.brand || existingProduct?.brandName || 'Local';
      autoGeneratedFields.push('brand');
    }

    // 3. Category (fallback from ProductFormModal: 'Men')
    let category = (rawRow.category || '').trim();
    if (!category) {
      category = existingProduct?.category || existingProduct?.categoryName || 'Men';
      autoGeneratedFields.push('category');
    }

    // 4. Article (auto-generated via parseCategoryPrefix & generateSuggestedArticle from src/utils/sku.ts)
    const catPfx = parseCategoryPrefix(category);
    const storeStandardArticle = generateSuggestedArticle(catPfx, rowProductId);
    let article = inputArticle;
    if (!article) {
      if (existingProduct?.article) {
        article = String(existingProduct.article).toUpperCase();
      } else {
        article = storeStandardArticle;
      }
      autoGeneratedFields.push('article');
    }
    usedArticles.add(article);

    // 5. Name / Title (fallback from ProductFormModal: cleanArticle)
    let name = (rawRow.name || '').trim();
    if (!name) {
      name = existingProduct?.name || article;
      autoGeneratedFields.push('name');
    }

    // 6. SKU (auto-generated via parseBrandPrefix & generateSku using storeStandardArticle so manual Article does not alter SKU)
    let sku = inputSku;
    if (!sku) {
      if (existingProduct?.sku) {
        sku = String(existingProduct.sku).toUpperCase();
      } else {
        const brandPfx = parseBrandPrefix(brand);
        sku = generateSku(brandPfx, storeStandardArticle, rowProductId);
        if (usedSkus.has(sku)) {
          sku = `${brandPfx}-${storeStandardArticle}-${rowProductId}`;
        }
      }
      autoGeneratedFields.push('sku');
    }
    usedSkus.add(sku);

    // 7. Barcode (auto-generated via generateCode128Barcode: [2-Letter Category]-[Exact Product ID], no prefix)
    let barcode = inputBarcode;
    if (!barcode) {
      if (existingProduct?.barcode) {
        barcode = String(existingProduct.barcode);
      } else {
        const catPfx = parseCategoryPrefix(category);
        let candidateId = rowProductId;
        let gen = generateCode128Barcode(candidateId, catPfx);
        while (usedBarcodes.has(gen.barcode)) {
          candidateId++;
          gen = generateCode128Barcode(candidateId, catPfx);
        }
        barcode = gen.barcode;
      }
      autoGeneratedFields.push('barcode');
    } else {
      const analysis = analyzeBarcode(barcode);
      if (!analysis.isValid) {
        validationErrors.barcode = analysis.error || 'Invalid barcode format.';
      }
    }
    usedBarcodes.add(barcode);

    if (!existingProduct) {
      nextCandidateId++;
    }

    // 8. Numeric validation & fallbacks for stock fields
    const rawStockStr = rawRow.total_stock ?? '';
    let total_stock = 0;
    if (rawStockStr === '') {
      total_stock = 0;
      autoGeneratedFields.push('total_stock');
    } else if (!/^-?\d+(\.\d+)?$/.test(rawStockStr)) {
      validationErrors.total_stock = `Invalid number "${rawStockStr}" in total_stock`;
    } else {
      const parsed = Math.round(Number(rawStockStr));
      if (parsed < 0) {
        validationErrors.total_stock = 'total_stock cannot be negative';
      } else {
        total_stock = parsed;
      }
    }

    const rawLowStockStr = rawRow.low_stock_limit ?? '';
    let low_stock_limit = defaultLowStockLimit;
    if (rawLowStockStr === '') {
      low_stock_limit = existingProduct?.lowStockLimit ?? defaultLowStockLimit;
      autoGeneratedFields.push('low_stock_limit');
    } else if (!/^-?\d+(\.\d+)?$/.test(rawLowStockStr)) {
      validationErrors.low_stock_limit = `Invalid number "${rawLowStockStr}" in low_stock_limit`;
    } else {
      const parsed = Math.round(Number(rawLowStockStr));
      if (parsed < 0) {
        validationErrors.low_stock_limit = 'low_stock_limit cannot be negative';
      } else {
        low_stock_limit = parsed;
      }
    }

    // 9. Numeric validation & fallbacks for pricing fields
    const parseNumericField = (
      fieldKey: 'cost_price' | 'selling_price' | 'min_price' | 'max_price',
      rawVal: string
    ): number | undefined => {
      if (rawVal === '') return undefined;
      if (!/^-?\d+(\.\d+)?$/.test(rawVal)) {
        validationErrors[fieldKey] = `Invalid numeric value "${rawVal}"`;
        return undefined;
      }
      const num = Number(rawVal);
      if (!Number.isFinite(num)) {
        validationErrors[fieldKey] = `Invalid numeric value "${rawVal}"`;
        return undefined;
      }
      return Math.round(num);
    };

    const parsedCost = parseNumericField('cost_price', rawRow.cost_price ?? '');
    const parsedSelling = parseNumericField('selling_price', rawRow.selling_price ?? '');
    const parsedMin = parseNumericField('min_price', rawRow.min_price ?? '');
    const parsedMax = parseNumericField('max_price', rawRow.max_price ?? '');

    let cost_price = parsedCost ?? 0;
    if (parsedCost === undefined && !validationErrors.cost_price) {
      cost_price =
        existingProduct?.costPrice ??
        existingProduct?.cost_price ??
        0;
      autoGeneratedFields.push('cost_price');
    }

    let effSelling = parsedSelling;
    let effMin = parsedMin;
    let effMax = parsedMax;

    if (pricingPolicy === 'FIXED') {
      if (effMax === undefined && !validationErrors.max_price) {
        effMax = effSelling ?? effMin ?? existingProduct?.maxPrice ?? existingProduct?.max_price ?? cost_price;
        autoGeneratedFields.push('max_price');
      }
      if (effMin === undefined && !validationErrors.min_price) {
        autoGeneratedFields.push('min_price');
      }
      if (effMax === undefined && !validationErrors.max_price) {
        autoGeneratedFields.push('max_price');
      }
    } else {
      if (effMin === undefined && !validationErrors.min_price) {
        effMin =
          effSelling ??
          existingProduct?.minPrice ??
          existingProduct?.min_price ??
          cost_price;
        autoGeneratedFields.push('min_price');
      }
      if (effMax === undefined && !validationErrors.max_price) {
        effMax =
          effSelling ??
          effMin ??
          existingProduct?.maxPrice ??
          existingProduct?.max_price ??
          cost_price;
        autoGeneratedFields.push('max_price');
      }
      if (effSelling === undefined && !validationErrors.selling_price) {
        effSelling = effMax;
        autoGeneratedFields.push('selling_price');
      }
    }

    let finalSellingPrice = effSelling ?? cost_price;
    let finalMinPrice = effMin ?? finalSellingPrice;
    let finalMaxPrice = effMax ?? finalSellingPrice;

    // Run strict Zod pricing validation if no raw numeric syntax error occurred on price fields
    const hasRawPriceSyntaxError = Boolean(
      validationErrors.cost_price ||
        validationErrors.selling_price ||
        validationErrors.min_price ||
        validationErrors.max_price
    );

    if (!hasRawPriceSyntaxError) {
      const priceValidation = validateAndNormalizeProductPricing({
        pricingPolicy,
        costPrice: cost_price,
        minPrice: effMin,
        maxPrice: effMax,
      });

      if (!priceValidation.success || !priceValidation.data) {
        if (priceValidation.fieldErrors.costPrice) {
          validationErrors.cost_price = priceValidation.fieldErrors.costPrice;
        }
        if (priceValidation.fieldErrors.sellingPrice) {
          validationErrors.selling_price = priceValidation.fieldErrors.sellingPrice;
        }
        if (priceValidation.fieldErrors.minPrice) {
          validationErrors.min_price = priceValidation.fieldErrors.minPrice;
        }
        if (priceValidation.fieldErrors.maxPrice) {
          validationErrors.max_price = priceValidation.fieldErrors.maxPrice;
        }
        if (
          !validationErrors.cost_price &&
          !validationErrors.selling_price &&
          !validationErrors.min_price &&
          !validationErrors.max_price &&
          priceValidation.error
        ) {
          validationErrors.selling_price = priceValidation.error;
        }
      } else {
        cost_price = priceValidation.data.costPrice;
        finalSellingPrice = priceValidation.data.sellingPrice;
        finalMinPrice = priceValidation.data.minPrice;
        finalMaxPrice = priceValidation.data.maxPrice;
      }
    }

    const isValid = Object.keys(validationErrors).length === 0;

    parsedRows.push({
      rowNumber: i,
      rawRow,
      article,
      name,
      brand,
      category,
      sku,
      barcode,
      cost_price,
      selling_price: finalSellingPrice,
      min_price: finalMinPrice,
      max_price: finalMaxPrice,
      total_stock,
      low_stock_limit,
      primary_image_url: rawRow.primary_image_url || '',
      description: rawRow.description || '',
      autoGeneratedFields,
      validationErrors,
      isValid,
      isDuplicate: Boolean(existingProduct),
      duplicateMatchType,
      existingProduct,
    });
  }

  return { rows: parsedRows };
}
